kind: Service
apiVersion: v1
metadata:
  name: gitops-hello-world-gcb-staging
  namespace: staging
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: gitops-hello-world-gcb
  type: ClusterIP
